name: Build Custom Studio Docker Image

on:
  push:
    paths:
      - '.github/workflows/build-studio.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Supabase Repository
        uses: actions/checkout@v4
        with:
          repository: supabase/supabase
          # Checkout the commit matching 2026.03.04-sha-0043607 to avoid regressions
          ref: 00436076bbd542f8e9593ae13811dee1cf353f19
          path: supabase

      - name: Patch IS_PLATFORM to true
        run: |
          sed -i "s/process.env.NEXT_PUBLIC_IS_PLATFORM === 'true'/true/g" supabase/apps/studio/lib/constants/index.ts
          sed -i "s/process.env.NEXT_PUBLIC_IS_PLATFORM === 'true'/true/g" supabase/apps/studio/next.config.js

      - name: Get lower case owner name
        id: owner
        run: echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./supabase
          file: ./supabase/apps/studio/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.owner }}/sb-studio:custom
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max
